### ISSUE TITLE
inserting none utc DateTime fails

### ISSUE THREAD

**Issue by mark1010** [dart-lang/gcloud#34]
I’m adapting the server components of pub-dartlang-dart to run my own project without the Docker.

I have server_io.dart working, connecting to the db. When running in this ‘mode’, a DateTime written to a model object with the @DateTimeProperty annotation fails when the DateTime is not Utc.

This works:
````
Future<AcsSession> createSession(AcsUser user) {
  var now = new DateTime.now().toUtc();
  AcsSession s = new AcsSession()
    ..userKey = user.key
    ..created = now
    ..expires = now.add(new Duration(hours:2));
  return db.commit(inserts:[s]).then((_) => s);
}
````
This fails:

````
Future<AcsSession> createSession(AcsUser user) {
  var now = new DateTime.now();
  AcsSession s = new AcsSession()
    ..userKey = user.key
    ..created = now
    ..expires = now.add(new Duration(hours:2));
  return db.commit(inserts:[s]).then((_) => s);
}
````
With…

````
Unhandled exception:
Uncaught Error: ApplicationError: Invalid value for: Invalid format: "2015-09-17T18:28:11.146" is malformed at ".146"
Stack Trace:
#0      _validateResponse.<anonymous closure> (package:_discoveryapis_commons/src/clients.dart:880:11)
#1      _rootRunUnary (dart:async/zone.dart:911)
#2      _CustomZone.runUnary (dart:async/zone.dart:811)
#3      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:494)
#4      _Future._propagateToListeners (dart:async/future_impl.dart:577)
#5      _Future._complete (dart:async/future_impl.dart:358)
#6      _cancelAndValue (dart:async/stream_pipe.dart:62)
#7      Stream.first.<anonymous closure> (dart:async/stream.dart:937)
#8      _rootRunUnary (dart:async/zone.dart:911)
#9      _CustomZone.runUnary (dart:async/zone.dart:811)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:717)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:270)
#13     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67)
.....
#100    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:895)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:43)
#2      _microtaskLoopEntry (dart:async/schedule_microtask.dart:52)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:394)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
````

appengine 0.3.1+1
gcloud 0.2.0+7
_discoveryapis_commons 0.1.1
googleapis 0.15.0

**Comment by mkustermann** [comment]
Generally speaking it is advisable to store `DateTime` objects always as UTC into a database. The reader of a `DateTime` value simply cannot know at which time it was written, since it might be in a different time zone.

By using `server_io.dart` you are most likely using `package:gcloud/src/datastore_impl.dart`, which in return uses [package:googleapis_beta/datastore/v1beta2.dart](http://www.dartdocs.org/documentation/googleapis_beta/0.19.0/index.html#googleapis_beta/googleapis_beta-datastore-v1beta2.Property@id_dateTimeValue). The documentation of this API doesn't directly indicate whether non-UTC date times are allowed. Though the more general *discovery API* (under which the datastore API falls) is described [here](https://developers.google.com/discovery/v1/type-format?hl=en) and states that date-time formats must be `An RFC3339 timestamp in UTC time`.

Hope this helps understand the error you are getting back from the server. I'm closing this issue as there is not much we could do about it I think.
