### ISSUE TITLE
Projection queries

### ISSUE THREAD

**Issue by martflu** [dart-lang/gcloud#46]
Would it be possible to add [projection queries](https://cloud.google.com/datastore/docs/concepts/queries#projection_queries)?
e.g. key only queries

> It is often more economical to do a keys-only query first, and then fetch a subset of entities from the results, rather than executing a general query which may fetch more entities than you actually need.

**Comment by enyo** [comment]
@jonasfj Am I right to assume that this is still not available? We can't do any highly efficient "keys-only" queries with the gcloud library?
In our project we need to select a list of objects in a specific time range. Since datastore doesn't allow to do a query in a specific time range, the recommended approach I've seen everywhere is to simply do a "keys-only" query for >time and <time and then remove all keys that are not in both of the sets. This is not achievable with this library right? Is there another way to query a time range then?

**Comment by jonasfj** [comment]
It's not available in this package. You can do it directly with `package:googleapis`.
