### ISSUE TITLE
FloatProperty, etc...

### ISSUE THREAD

**Issue by enyo** [dart-lang/gcloud#7]
In the [Python API](https://cloud.google.com/appengine/docs/python/datastore/typesandpropertyclasses) there are lots of other property types.

Will those be implemented in Dart as well?

**Comment by lukechurch** [comment]
@mkustermann Did this land at all?

Because of the 500 char limit, I've recently found a need for the TextProperty again, but I have a feeling that it's not as simple as just adding 

class TextProperty extends db.PrimitiveProperty {
const TextProperty(
{String propertyName, bool required: false, bool indexed: false})
: super(propertyName: propertyName, required: required, indexed: indexed);

bool validate(db.ModelDB db, Object value)
=> super.validate(db, value) && (value == null || value is String);
}

or you would have done it.

Being able to read TextProperties is pretty important for one of my use cases, so if there's something I can do to help get this landed, please let me know. Thanks!

**Comment by mkustermann** [comment]
@lukechurch The `DoubleProperty`, `BlobProperty` and `ModelKeyProperty` properties landed.

Strings of more than 500 characters cannot be indexed on AppEngine. Did you try turning indexing off? [i.e. `@db.StringProperty(indexed: false) String myLongString`]

**Comment by mkustermann** [comment]
Since this issue was originally about floating point property and we've added that as `DoubleProperty` I'll close this issue.
